import { Player } from './types';

export const INITIAL_PLAYERS: Player[] = [
  {
    "id": "p1",
    "name": "Kumuda Bopaiah",
    "gender": "Female",
    "role": "",
    "badminton": 70,
    "carroms": 0,
    "cricket": 70,
    "football": 0,
    "tableTennis": 0,
    "skillRating": 70,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/Kumuda%20Pic_Kumuda%20Bopaiah.png",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p2",
    "name": "sachin s shivabugadi",
    "gender": "Male",
    "role": "",
    "badminton": 40,
    "carroms": 40,
    "cricket": 40,
    "football": 40,
    "tableTennis": 0,
    "skillRating": 40,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/DSC_1103%20copy_Sachin%20Shambhaji%20Shi%202.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p3",
    "name": "Ragul Murugan",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 40,
    "cricket": 40,
    "football": 40,
    "tableTennis": 40,
    "skillRating": 46,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/IMG_7646_Ragul%20M.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p4",
    "name": "Mohit B",
    "gender": "Male",
    "role": "",
    "badminton": 40,
    "carroms": 40,
    "cricket": 70,
    "football": 70,
    "tableTennis": 95,
    "skillRating": 63,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/Mohit_Mohit%20B%201.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p5",
    "name": "Akash Sharma",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 95,
    "cricket": 70,
    "football": 40,
    "tableTennis": 95,
    "skillRating": 74,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/1000127508_Akash%20Sharma%201.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p6",
    "name": "Deepak Kumar Pandit",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 95,
    "cricket": 0,
    "football": 0,
    "tableTennis": 95,
    "skillRating": 86.7,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/815ba595-a9fe-4970-9b90-4b50d64fd4c7_Deepak%20Kumar%20Pandit%201.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p7",
    "name": "Dhananjay Dharne",
    "gender": "Male",
    "role": "",
    "badminton": 40,
    "carroms": 40,
    "cricket": 70,
    "football": 40,
    "tableTennis": 70,
    "skillRating": 52,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/DJ_Dhananjay%20Suhas%20Dhar.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p8",
    "name": "Keerthana B R",
    "gender": "Female",
    "role": "",
    "badminton": 70,
    "carroms": 70,
    "cricket": 40,
    "football": 40,
    "tableTennis": 70,
    "skillRating": 58,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/WhatsApp%20Image%202026-07-06%20at%2012.49.38_Keerthana%20B%20R.jpeg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p9",
    "name": "Sanjai N",
    "gender": "Male",
    "role": "",
    "badminton": 0,
    "carroms": 95,
    "cricket": 95,
    "football": 70,
    "tableTennis": 0,
    "skillRating": 86.7,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/IMG_2026_Sanjai%20N.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p10",
    "name": "Kiran Antony",
    "gender": "Male",
    "role": "",
    "badminton": 0,
    "carroms": 70,
    "cricket": 70,
    "football": 70,
    "tableTennis": 0,
    "skillRating": 70,
    "falaLeague": "No",
    "photoUrl": "/players/Kiran Antony.jpeg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p11",
    "name": "BINU PAUL",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 0,
    "cricket": 40,
    "football": 70,
    "tableTennis": 40,
    "skillRating": 55,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/ABLR0507%20BinuPaul_Binu%20Paul.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p12",
    "name": "Dileep Kumar G",
    "gender": "Male",
    "role": "",
    "badminton": 95,
    "carroms": 70,
    "cricket": 95,
    "football": 40,
    "tableTennis": 70,
    "skillRating": 74,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/Dileep_Kumar_Dileep%20Kumar%20G%20Reddy.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p13",
    "name": "Rani Devi",
    "gender": "Female",
    "role": "",
    "badminton": 40,
    "carroms": 70,
    "cricket": 40,
    "football": 0,
    "tableTennis": 40,
    "skillRating": 47.5,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/20230927193243_IMG_3472_Rani%20Devi.JPG",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p14",
    "name": "Venkat Ravada",
    "gender": "Male",
    "role": "",
    "badminton": 40,
    "carroms": 40,
    "cricket": 70,
    "football": 40,
    "tableTennis": 40,
    "skillRating": 46,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/venkat-id-card_Ravada%20Venkataramana.png",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p15",
    "name": "Vishnu Benny",
    "gender": "Male",
    "role": "",
    "badminton": 0,
    "carroms": 70,
    "cricket": 95,
    "football": 70,
    "tableTennis": 70,
    "skillRating": 76.2,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/IMG_4699_Vishnu%20Benny.jpeg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p16",
    "name": "Anoop Kumar Mittapelli",
    "gender": "Male",
    "role": "",
    "badminton": 40,
    "carroms": 40,
    "cricket": 95,
    "football": 0,
    "tableTennis": 40,
    "skillRating": 53.8,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/1758718530466_Anoop%20Kumar%20Mittapel.pdf",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p17",
    "name": "Madhumurthy K",
    "gender": "Male",
    "role": "",
    "badminton": 40,
    "carroms": 40,
    "cricket": 70,
    "football": 40,
    "tableTennis": 70,
    "skillRating": 52,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/MadhuKollu_Photo_Madhu%20Murthy%20Kollu.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p18",
    "name": "Saurabh Negi",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 40,
    "cricket": 70,
    "football": 70,
    "tableTennis": 70,
    "skillRating": 64,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/PassPortPic_Saurabh%20Negi.png",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p19",
    "name": "AKHIL M S",
    "gender": "Male",
    "role": "",
    "badminton": 95,
    "carroms": 70,
    "cricket": 95,
    "football": 70,
    "tableTennis": 70,
    "skillRating": 80,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/IMG_4595_Akhil%20MS.JPG",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p20",
    "name": "Praveen Kumar",
    "gender": "Male",
    "role": "",
    "badminton": 40,
    "carroms": 40,
    "cricket": 40,
    "football": 40,
    "tableTennis": 40,
    "skillRating": 40,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/Praveen%20Kumar_Praveen%20Kumar%20Bhaska.png",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p21",
    "name": "Aditya Mehta",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 40,
    "cricket": 70,
    "football": 70,
    "tableTennis": 70,
    "skillRating": 64,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/WhatsApp%20Image%202026-06-29%20at%203.24.34%20PM_Aditya%20Mehta.jpeg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p22",
    "name": "Vishal Khanna S",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 40,
    "cricket": 70,
    "football": 0,
    "tableTennis": 40,
    "skillRating": 55,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/WhatsApp%20Image%202026-06-29%20at%203.44.07%20PM_Vishal%20Khanna%20S.jpeg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p23",
    "name": "Bhavana Balachandran",
    "gender": "Female",
    "role": "",
    "badminton": 70,
    "carroms": 70,
    "cricket": 70,
    "football": 0,
    "tableTennis": 40,
    "skillRating": 62.5,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/Bhavana%20Balachandran_Bhavana%20Balachandran.png",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p24",
    "name": "Raveendra Bista",
    "gender": "Male",
    "role": "",
    "badminton": 95,
    "carroms": 0,
    "cricket": 95,
    "football": 40,
    "tableTennis": 70,
    "skillRating": 75,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/IMG_20251006_223959_760_Raveendra%20Bista.png",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p25",
    "name": "Anmol Narang",
    "gender": "Male",
    "role": "",
    "badminton": 0,
    "carroms": 0,
    "cricket": 0,
    "football": 70,
    "tableTennis": 0,
    "skillRating": 70,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/DSC_0494_Anmol%20Narang.JPG",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p26",
    "name": "Pavel Ray",
    "gender": "Male",
    "role": "",
    "badminton": 40,
    "carroms": 40,
    "cricket": 40,
    "football": 40,
    "tableTennis": 0,
    "skillRating": 40,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/Screenshot%202026-06-29%20at%204.20.30%E2%80%AFPM_Pavel%20Ray.png",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p27",
    "name": "Jayesh Jain",
    "gender": "Male",
    "role": "",
    "badminton": 40,
    "carroms": 0,
    "cricket": 95,
    "football": 95,
    "tableTennis": 0,
    "skillRating": 76.7,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/Image_Jayesh%20Jain.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p28",
    "name": "Chintapalli Manikanta",
    "gender": "Male",
    "role": "",
    "badminton": 40,
    "carroms": 70,
    "cricket": 70,
    "football": 40,
    "tableTennis": 70,
    "skillRating": 58,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/Photo_11zon_Manikanta%20Chintapall.png",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p29",
    "name": "Glenvin Anil Rosario",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 0,
    "cricket": 70,
    "football": 40,
    "tableTennis": 40,
    "skillRating": 55,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/IMG_3392_Glenvin%20Anil%20Rosario.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p30",
    "name": "Shalini P",
    "gender": "Female",
    "role": "",
    "badminton": 95,
    "carroms": 70,
    "cricket": 40,
    "football": 40,
    "tableTennis": 70,
    "skillRating": 63,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/IMG_7081%20Small_Shalini%20P.jpeg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p31",
    "name": "Harshkumar Rajeshbhai Patel",
    "gender": "Male",
    "role": "",
    "badminton": 40,
    "carroms": 40,
    "cricket": 70,
    "football": 40,
    "tableTennis": 40,
    "skillRating": 46,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/images_Harshkumar%20Rajeshbha.jpeg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p32",
    "name": "Navya Jaideep",
    "gender": "Female",
    "role": "",
    "badminton": 70,
    "carroms": 70,
    "cricket": 40,
    "football": 70,
    "tableTennis": 40,
    "skillRating": 58,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/MyPic_Navya%20Jaideep.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p33",
    "name": "Sumit Kumar",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 40,
    "cricket": 40,
    "football": 40,
    "tableTennis": 40,
    "skillRating": 46,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/IMG_6930_Sumit%20Kumar.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p34",
    "name": "Ankit Ammanagi",
    "gender": "Male",
    "role": "",
    "badminton": 0,
    "carroms": 0,
    "cricket": 70,
    "football": 70,
    "tableTennis": 70,
    "skillRating": 70,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/Image_Ankit%20Ammanagi.jpeg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p35",
    "name": "RAKSHA PRASAD M",
    "gender": "Female",
    "role": "",
    "badminton": 70,
    "carroms": 40,
    "cricket": 40,
    "football": 40,
    "tableTennis": 70,
    "skillRating": 52,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/Profile_photo_Raksha%20Prasad.jpeg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p36",
    "name": "Suraj Hiremath",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 40,
    "cricket": 70,
    "football": 70,
    "tableTennis": 70,
    "skillRating": 64,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/WhatsApp%20Image%202026-06-30%20at%209.30.23%20AM_Suraj%20Hiremath.jpeg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p37",
    "name": "Venkata Purandhar Chitteti",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 70,
    "cricket": 70,
    "football": 40,
    "tableTennis": 0,
    "skillRating": 62.5,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/image_purandhar_Chitteti%20Venkata%20Pur.jpeg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p38",
    "name": "Disha V",
    "gender": "Female",
    "role": "",
    "badminton": 70,
    "carroms": 0,
    "cricket": 70,
    "football": 40,
    "tableTennis": 0,
    "skillRating": 60,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/IMG_8322_Disha%20V.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p39",
    "name": "Vishwanath Budugumpi",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 70,
    "cricket": 95,
    "football": 40,
    "tableTennis": 70,
    "skillRating": 69,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/WhatsApp%20Image%202026-06-30%20at%2011.59.39_Vishwanath%20Budugumpi.jpeg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p40",
    "name": "Kirti Dhanapune",
    "gender": "Female",
    "role": "",
    "badminton": 40,
    "carroms": 40,
    "cricket": 40,
    "football": 0,
    "tableTennis": 70,
    "skillRating": 47.5,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/kirti_Kirti%20Dhanapune.jpeg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p41",
    "name": "Sachin Gupta",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 70,
    "cricket": 95,
    "football": 40,
    "tableTennis": 70,
    "skillRating": 69,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/Screenshot%202026-06-30%20at%2012.21.06%E2%80%AFPM_Sachin%20Gupta.png",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p42",
    "name": "Nandan R",
    "gender": "Male",
    "role": "",
    "badminton": 0,
    "carroms": 40,
    "cricket": 0,
    "football": 0,
    "tableTennis": 40,
    "skillRating": 40,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/Image_Nandan%20R.jpeg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p43",
    "name": "Arko Mitra",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 40,
    "cricket": 40,
    "football": 70,
    "tableTennis": 40,
    "skillRating": 52,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/Screenshot%202026-06-30%20at%2012.49.26%E2%80%AFPM_Arko%20Antony%20Mitra.png",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p44",
    "name": "Arjun ghosh",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 0,
    "cricket": 0,
    "football": 70,
    "tableTennis": 70,
    "skillRating": 70,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/WhatsApp%20Image%202026-06-30%20at%2012.50.53%20PM_Arjun%20Ghosh.jpeg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p45",
    "name": "Aman Kalal",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 40,
    "cricket": 40,
    "football": 40,
    "tableTennis": 70,
    "skillRating": 52,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/A4E2BBB3-36BE-416F-B021-2A19440E0266_Aman%20Kalal.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p46",
    "name": "Neetha I J",
    "gender": "Female",
    "role": "",
    "badminton": 70,
    "carroms": 0,
    "cricket": 0,
    "football": 0,
    "tableTennis": 0,
    "skillRating": 70,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/Neetha%20Pic_Neetha%20IJ.jpeg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p47",
    "name": "Rahul Kiran",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 40,
    "cricket": 0,
    "football": 0,
    "tableTennis": 40,
    "skillRating": 50,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/Media_Rahul%20Kiran.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p48",
    "name": "Prasanna Kumar R",
    "gender": "Male",
    "role": "",
    "badminton": 40,
    "carroms": 40,
    "cricket": 40,
    "football": 40,
    "tableTennis": 40,
    "skillRating": 40,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/Prasanna_Prasanna%20Kumar%20R.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p49",
    "name": "Vijay Anantpur",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 0,
    "cricket": 70,
    "football": 40,
    "tableTennis": 70,
    "skillRating": 62.5,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/IMG_0490_Vijay%20Anantpur.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": true
  },
  {
    "id": "p50",
    "name": "Viswajith K N",
    "gender": "Male",
    "role": "",
    "badminton": 0,
    "carroms": 70,
    "cricket": 70,
    "football": 0,
    "tableTennis": 0,
    "skillRating": 70,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/IMG_7200_Viswajith%20K%20N.jpeg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p51",
    "name": "Lakshya Ruhela",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 70,
    "cricket": 95,
    "football": 70,
    "tableTennis": 70,
    "skillRating": 75,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/20241017_215226_Lakshya%20Ruhela.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p52",
    "name": "Vinayak Bhandage",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 40,
    "cricket": 70,
    "football": 70,
    "tableTennis": 40,
    "skillRating": 58,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/IMG-20240611-WA0092~2_Vinayak%20Bhandage.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p53",
    "name": "Madhu",
    "gender": "Male",
    "role": "",
    "badminton": 0,
    "carroms": 70,
    "cricket": 95,
    "football": 70,
    "tableTennis": 0,
    "skillRating": 78.3,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/Screenshot%202026-06-30%20at%203.38.09%E2%80%AFPM_Madhu.png",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p54",
    "name": "Vishnu Mohan",
    "gender": "Male",
    "role": "",
    "badminton": 40,
    "carroms": 40,
    "cricket": 70,
    "football": 70,
    "tableTennis": 0,
    "skillRating": 55,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/WhatsApp%20Image%202026-06-30%20at%2015.45.46_Vishnu%20Mohan.jpeg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p55",
    "name": "Pratyush Prakash",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 70,
    "cricket": 70,
    "football": 40,
    "tableTennis": 40,
    "skillRating": 58,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/20250413_182047_Pratyush%20Prakash.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p56",
    "name": "Tushar Tekta",
    "gender": "Male",
    "role": "",
    "badminton": 40,
    "carroms": 70,
    "cricket": 95,
    "football": 40,
    "tableTennis": 70,
    "skillRating": 63,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/Media_Tushar%20Tekta.jpeg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p57",
    "name": "Sushmitha M",
    "gender": "Female",
    "role": "",
    "badminton": 0,
    "carroms": 0,
    "cricket": 0,
    "football": 0,
    "tableTennis": 70,
    "skillRating": 70,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/sush_Sushmitha%20M.png",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p58",
    "name": "Rashmi Kadam",
    "gender": "Female",
    "role": "",
    "badminton": 40,
    "carroms": 40,
    "cricket": 40,
    "football": 0,
    "tableTennis": 0,
    "skillRating": 40,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/Rashmi%20Kadam_Rashmi%20Kadam.jpeg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p59",
    "name": "Nisha Naik",
    "gender": "Female",
    "role": "",
    "badminton": 70,
    "carroms": 70,
    "cricket": 0,
    "football": 40,
    "tableTennis": 70,
    "skillRating": 62.5,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/IMG20250227184011_Nisha%20Naik.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p60",
    "name": "Iliyas Mulla",
    "gender": "Male",
    "role": "",
    "badminton": 40,
    "carroms": 0,
    "cricket": 40,
    "football": 40,
    "tableTennis": 40,
    "skillRating": 40,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/1000180576_Mulla%20Iliyas.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": true
  },
  {
    "id": "p61",
    "name": "Riddhi Bastwadkar",
    "gender": "Female",
    "role": "",
    "badminton": 70,
    "carroms": 40,
    "cricket": 0,
    "football": 0,
    "tableTennis": 0,
    "skillRating": 55,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/Image%20from%20iOS_Riddhi%20Bastwadkar.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p62",
    "name": "Santosh Killamsetty",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 70,
    "cricket": 0,
    "football": 70,
    "tableTennis": 70,
    "skillRating": 70,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/WhatsApp%20Image%202026-07-01%20at%2011.14.16_Santosh%20Killamsetty.jpeg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p63",
    "name": "Koushik Bhattacharya",
    "gender": "Male",
    "role": "",
    "badminton": 40,
    "carroms": 40,
    "cricket": 40,
    "football": 40,
    "tableTennis": 40,
    "skillRating": 40,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/koushik_pic_Koushik%20Bhattacharya.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p64",
    "name": "HIMANSU SEKHAR SAHOO",
    "gender": "Male",
    "role": "",
    "badminton": 40,
    "carroms": 70,
    "cricket": 70,
    "football": 70,
    "tableTennis": 40,
    "skillRating": 58,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/41213040_1616356501804259_2449291734329327616_Himansu%20Sekhar%20Sahoo.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p65",
    "name": "Sri Sathwik",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 40,
    "cricket": 70,
    "football": 40,
    "tableTennis": 40,
    "skillRating": 52,
    "falaLeague": "Yes",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/384dad53-0f31-4856-a205-5e052563fc7f_Sri%20Srinivasa%20Ganga.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p66",
    "name": "Ujwal Manjunath",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 40,
    "cricket": 40,
    "football": 0,
    "tableTennis": 70,
    "skillRating": 55,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/T078JK1SS-UNVGC30JC-a7369e3b9dd0-512_Ujwal%20Manjunath.jpeg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p67",
    "name": "Dharnendra L V",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 70,
    "cricket": 70,
    "football": 70,
    "tableTennis": 70,
    "skillRating": 70,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/IMG_20211119_174854%20(1)_Dharnendra%20L%20V.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p68",
    "name": "Nitish Kumar Kushwaha",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 40,
    "cricket": 0,
    "football": 0,
    "tableTennis": 0,
    "skillRating": 55,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/DSC02628%20(1)_Nitish%20Kumar%20Kushwah.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p69",
    "name": "Gokul Raja",
    "gender": "Male",
    "role": "",
    "badminton": 40,
    "carroms": 70,
    "cricket": 40,
    "football": 40,
    "tableTennis": 70,
    "skillRating": 52,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/20250816_123128_Gokul%20Raja%20TS.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p70",
    "name": "Ganesh Sanjay Margale",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 40,
    "cricket": 40,
    "football": 40,
    "tableTennis": 40,
    "skillRating": 46,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/IMG_0322_Ganesh%20Sanjay%20Margal.PNG",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p71",
    "name": "Don Chakkappan",
    "gender": "Male",
    "role": "",
    "badminton": 0,
    "carroms": 40,
    "cricket": 70,
    "football": 0,
    "tableTennis": 0,
    "skillRating": 55,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/don_Don%20Chakkappan.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p72",
    "name": "Maddali Sudheer",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 40,
    "cricket": 95,
    "football": 95,
    "tableTennis": 70,
    "skillRating": 74,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/WhatsApp%20Image%202026-07-02%20at%2012.14.18_Maddali%20Sudheer.jpeg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p73",
    "name": "Kiran Bendekere",
    "gender": "Male",
    "role": "",
    "badminton": 0,
    "carroms": 0,
    "cricket": 70,
    "football": 40,
    "tableTennis": 70,
    "skillRating": 60,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/ABLR0606%20Kiran%20Bendekere_Kiran%20Bendekere.png",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p74",
    "name": "Sourav Kumar",
    "gender": "Male",
    "role": "",
    "badminton": 40,
    "carroms": 70,
    "cricket": 70,
    "football": 40,
    "tableTennis": 70,
    "skillRating": 58,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/Sourav_image_Sourav%20Kumar.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p75",
    "name": "Lohit V",
    "gender": "Male",
    "role": "",
    "badminton": 40,
    "carroms": 70,
    "cricket": 40,
    "football": 0,
    "tableTennis": 0,
    "skillRating": 50,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/IMG20250926142852_Original_Lohit%20V.jpeg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p76",
    "name": "Anupam Kumar",
    "gender": "Male",
    "role": "",
    "badminton": 95,
    "carroms": 70,
    "cricket": 95,
    "football": 40,
    "tableTennis": 70,
    "skillRating": 74,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/20260501_171619_Anupam%20Kumar.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p77",
    "name": "Varun HS",
    "gender": "Male",
    "role": "",
    "badminton": 0,
    "carroms": 70,
    "cricket": 40,
    "football": 0,
    "tableTennis": 70,
    "skillRating": 60,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/Image%20from%20iOS%20(1)_Varun%20HS.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p78",
    "name": "Vipin U N",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 40,
    "cricket": 70,
    "football": 0,
    "tableTennis": 40,
    "skillRating": 55,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/76440_Vipin%20UN.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p79",
    "name": "Hrishikesh S Raj",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 40,
    "cricket": 70,
    "football": 70,
    "tableTennis": 40,
    "skillRating": 58,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/IMG-20250507-WA0165_Hrishikesh%20Raj.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p80",
    "name": "Udhay",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 40,
    "cricket": 70,
    "football": 40,
    "tableTennis": 70,
    "skillRating": 58,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/file_00000000cc60720b9034931c59d290a8_Udhaya%20Kumar.png",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p81",
    "name": "Yash Pendse",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 70,
    "cricket": 70,
    "football": 40,
    "tableTennis": 70,
    "skillRating": 64,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/yash_pendse_photo_Yash%20Pendse.jpeg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": true
  },
  {
    "id": "p82",
    "name": "Shubhi Goyal",
    "gender": "Male",
    "role": "",
    "badminton": 0,
    "carroms": 40,
    "cricket": 40,
    "football": 0,
    "tableTennis": 0,
    "skillRating": 40,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/IMG_20260703_112054740~2_Shubhi%20Goyal.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p83",
    "name": "Pratik G Desai",
    "gender": "Male",
    "role": "",
    "badminton": 40,
    "carroms": 40,
    "cricket": 40,
    "football": 40,
    "tableTennis": 40,
    "skillRating": 40,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/IMG_3746_Pratik%20Desai.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p84",
    "name": "Vishant Singh",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 70,
    "cricket": 95,
    "football": 95,
    "tableTennis": 70,
    "skillRating": 80,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/Media%20(1)%20(1)_Vishant%20Singh.jpeg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p85",
    "name": "Suraj Pakhare",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 40,
    "cricket": 70,
    "football": 40,
    "tableTennis": 40,
    "skillRating": 52,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/20260621_131059_Suraj%20Pakhare.png",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p86",
    "name": "D V Dileep",
    "gender": "Male",
    "role": "",
    "badminton": 40,
    "carroms": 40,
    "cricket": 40,
    "football": 40,
    "tableTennis": 0,
    "skillRating": 40,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/DSC_3907_D%20V%20Dileep.JPG",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p87",
    "name": "Gutta Amarnath",
    "gender": "Male",
    "role": "",
    "badminton": 0,
    "carroms": 0,
    "cricket": 40,
    "football": 0,
    "tableTennis": 0,
    "skillRating": 40,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/pic_Amarnath%20Gutta.png",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p88",
    "name": "Vikram Gurubelli",
    "gender": "Male",
    "role": "",
    "badminton": 40,
    "carroms": 40,
    "cricket": 0,
    "football": 0,
    "tableTennis": 40,
    "skillRating": 40,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/IMG_20260703_153030_Gurubelli%20Vikram.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p89",
    "name": "Revathi",
    "gender": "Female",
    "role": "",
    "badminton": 40,
    "carroms": 40,
    "cricket": 0,
    "football": 0,
    "tableTennis": 40,
    "skillRating": 40,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/IMG_9618_Revathi%20Mallikarjun.jpeg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p90",
    "name": "Rajesh Vavilala",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 70,
    "cricket": 95,
    "football": 40,
    "tableTennis": 0,
    "skillRating": 68.8,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/Screenshot_2026_0703_155950_Rajesh%20Vavilala.png",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p91",
    "name": "Chennam Yuvaraju",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 0,
    "cricket": 40,
    "football": 0,
    "tableTennis": 0,
    "skillRating": 55,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/ABLR0491_Chennam%20Yuvaraju.JPG",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p92",
    "name": "K C Santosh",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 40,
    "cricket": 70,
    "football": 40,
    "tableTennis": 0,
    "skillRating": 55,
    "falaLeague": "No",
    "photoUrl": "",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p93",
    "name": "Siddarth S Desai",
    "gender": "Male",
    "role": "",
    "badminton": 40,
    "carroms": 40,
    "cricket": 40,
    "football": 40,
    "tableTennis": 40,
    "skillRating": 40,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/IMG-20230515-WA0002~2_Siddarth%20Desai.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p94",
    "name": "Mahesh Nironi",
    "gender": "Male",
    "role": "",
    "badminton": 40,
    "carroms": 95,
    "cricket": 70,
    "football": 0,
    "tableTennis": 0,
    "skillRating": 68.3,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/mahesh_Mahesh%20Nironi.png",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p95",
    "name": "Manshu Saingar",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 70,
    "cricket": 70,
    "football": 40,
    "tableTennis": 0,
    "skillRating": 62.5,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/Image%20from%20iOS_Manshu%20Saingar.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p96",
    "name": "Abhisek Mallick",
    "gender": "Male",
    "role": "",
    "badminton": 40,
    "carroms": 40,
    "cricket": 70,
    "football": 40,
    "tableTennis": 40,
    "skillRating": 46,
    "falaLeague": "No",
    "photoUrl": "",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p97",
    "name": "Maqsood Desai",
    "gender": "Male",
    "role": "",
    "badminton": 40,
    "carroms": 40,
    "cricket": 40,
    "football": 40,
    "tableTennis": 70,
    "skillRating": 46,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/my-passport-photo_Maqsood%20Desai.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p98",
    "name": "Ayushi Kushwaha",
    "gender": "Male",
    "role": "",
    "badminton": 40,
    "carroms": 40,
    "cricket": 40,
    "football": 40,
    "tableTennis": 40,
    "skillRating": 40,
    "falaLeague": "No",
    "photoUrl": "",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p99",
    "name": "Thoshima Kaveramma B S",
    "gender": "Female",
    "role": "",
    "badminton": 0,
    "carroms": 70,
    "cricket": 0,
    "football": 70,
    "tableTennis": 0,
    "skillRating": 70,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/Thoshima_Thoshima%20Kaveramma.png",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p100",
    "name": "Shruti L Gataraddihal",
    "gender": "Female",
    "role": "",
    "badminton": 40,
    "carroms": 40,
    "cricket": 40,
    "football": 0,
    "tableTennis": 0,
    "skillRating": 40,
    "falaLeague": "No",
    "photoUrl": "",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p101",
    "name": "Praveen G Kalmath",
    "gender": "Male",
    "role": "",
    "badminton": 0,
    "carroms": 40,
    "cricket": 70,
    "football": 70,
    "tableTennis": 0,
    "skillRating": 60,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/Praveen%20G%20Kalmath_Praveen%20G%20Kalmath.jpeg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p102",
    "name": "Ashish Kaushal",
    "gender": "Male",
    "role": "",
    "badminton": 40,
    "carroms": 40,
    "cricket": 0,
    "football": 40,
    "tableTennis": 0,
    "skillRating": 40,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/68995cfa-91f6-436f-904a-6553d9972b8a~1_Ashish%20Kaushal.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p103",
    "name": "Jagadishwari S",
    "gender": "Female",
    "role": "",
    "badminton": 40,
    "carroms": 40,
    "cricket": 40,
    "football": 40,
    "tableTennis": 40,
    "skillRating": 40,
    "falaLeague": "No",
    "photoUrl": "",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p104",
    "name": "Govind S",
    "gender": "Male",
    "role": "",
    "badminton": 40,
    "carroms": 0,
    "cricket": 0,
    "football": 70,
    "tableTennis": 0,
    "skillRating": 55,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/1572330914192_Govind%20S.jpeg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p105",
    "name": "Vishnu K P",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 70,
    "cricket": 0,
    "football": 70,
    "tableTennis": 70,
    "skillRating": 70,
    "falaLeague": "No",
    "photoUrl": "",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p106",
    "name": "Peethani RaviRaja",
    "gender": "Male",
    "role": "",
    "badminton": 95,
    "carroms": 70,
    "cricket": 95,
    "football": 70,
    "tableTennis": 70,
    "skillRating": 80,
    "falaLeague": "Yes",
    "photoUrl": "",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p107",
    "name": "Shaik Rahul",
    "gender": "Male",
    "role": "",
    "badminton": 0,
    "carroms": 40,
    "cricket": 95,
    "football": 0,
    "tableTennis": 0,
    "skillRating": 67.5,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/tempImagezcSQmV_Shaik%20Rahul.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p108",
    "name": "Kalp Agarwal",
    "gender": "Male",
    "role": "",
    "badminton": 40,
    "carroms": 0,
    "cricket": 0,
    "football": 0,
    "tableTennis": 0,
    "skillRating": 40,
    "falaLeague": "No",
    "photoUrl": "",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p109",
    "name": "aryan choudhary",
    "gender": "Male",
    "role": "",
    "badminton": 40,
    "carroms": 40,
    "cricket": 40,
    "football": 40,
    "tableTennis": 40,
    "skillRating": 40,
    "falaLeague": "No",
    "photoUrl": "",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p110",
    "name": "ANMOL RAJPUT",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 0,
    "cricket": 40,
    "football": 40,
    "tableTennis": 40,
    "skillRating": 47.5,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/WhatsApp%20Image%202026-04-11%20at%2010.44.46%20AM%20(2)_Anmol%20Rajput.jpeg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p111",
    "name": "Souvik Biswas",
    "gender": "Male",
    "role": "",
    "badminton": 40,
    "carroms": 40,
    "cricket": 70,
    "football": 70,
    "tableTennis": 0,
    "skillRating": 55,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/WhatsApp%20Image%202026-07-07%20at%2013.02.37_Souvik%20Biswas.jpeg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p112",
    "name": "Bharath S",
    "gender": "Male",
    "role": "",
    "badminton": 40,
    "carroms": 0,
    "cricket": 0,
    "football": 0,
    "tableTennis": 40,
    "skillRating": 40,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/new%20pic_Bharath%20S.jpeg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p113",
    "name": "Agatya Panigrahy",
    "gender": "Male",
    "role": "",
    "badminton": 40,
    "carroms": 40,
    "cricket": 0,
    "football": 0,
    "tableTennis": 40,
    "skillRating": 40,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/Screenshot%202026-06-05%20at%202.16.22%E2%80%AFPM_Agatya%20Panigrahy.png",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p114",
    "name": "Rohith H",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 40,
    "cricket": 40,
    "football": 40,
    "tableTennis": 40,
    "skillRating": 46,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/photo_Rohith%20H.jpg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p115",
    "name": "Rupali Gangarde",
    "gender": "Female",
    "role": "",
    "badminton": 40,
    "carroms": 40,
    "cricket": 40,
    "football": 0,
    "tableTennis": 40,
    "skillRating": 40,
    "falaLeague": "No",
    "photoUrl": "",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p116",
    "name": "Kumuda Naik",
    "gender": "Female",
    "role": "",
    "badminton": 70,
    "carroms": 40,
    "cricket": 40,
    "football": 0,
    "tableTennis": 40,
    "skillRating": 47.5,
    "falaLeague": "No",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/IMG_8665_Kumuda%20Naik.jpeg",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p117",
    "name": "mahesh",
    "gender": "Male",
    "role": "",
    "badminton": 40,
    "carroms": 70,
    "cricket": 70,
    "football": 0,
    "tableTennis": 0,
    "skillRating": 60,
    "falaLeague": "Fsathwik",
    "photoUrl": "https://falabella-my.sharepoint.com/personal/kumuda_bopaiah_falabella_cl1/Documents/Aplicaciones/Microsoft%20Forms/Register%20for%20participating%20in%20Falaliga%2040/Question/Mahesh%20Chinchure_Mahesh%20Chinchure.JPG",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p118",
    "name": "Himanshu Jaiswal",
    "gender": "Male",
    "role": "",
    "badminton": 40,
    "carroms": 70,
    "cricket": 40,
    "football": 70,
    "tableTennis": 40,
    "skillRating": 52,
    "falaLeague": "No",
    "photoUrl": "",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p119",
    "name": "Vikhyath BM",
    "gender": "Male",
    "role": "",
    "badminton": 95,
    "carroms": 0,
    "cricket": 95,
    "football": 0,
    "tableTennis": 40,
    "skillRating": 76.7,
    "falaLeague": "No",
    "photoUrl": "",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p120",
    "name": "Naveen Vempati",
    "gender": "Male",
    "role": "",
    "badminton": 90,
    "carroms": 90,
    "cricket": 90,
    "football": 90,
    "tableTennis": 90,
    "skillRating": 90,
    "falaLeague": "Yes",
    "photoUrl": "",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": true
  },
  {
    "id": "p121",
    "name": "Shashank Poojary",
    "gender": "Male",
    "role": "",
    "badminton": 90,
    "carroms": 90,
    "cricket": 90,
    "football": 90,
    "tableTennis": 90,
    "skillRating": 90,
    "falaLeague": "Yes",
    "photoUrl": "",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": true
  },
  {
    "id": "p122",
    "name": "Satheesh Kumar K",
    "gender": "Male",
    "role": "",
    "badminton": 90,
    "carroms": 90,
    "cricket": 90,
    "football": 90,
    "tableTennis": 90,
    "skillRating": 90,
    "falaLeague": "Yes",
    "photoUrl": "",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": true
  },
  {
    "id": "p123",
    "name": "Tarani Prasad Pani",
    "gender": "Male",
    "role": "",
    "badminton": 90,
    "carroms": 90,
    "cricket": 90,
    "football": 90,
    "tableTennis": 90,
    "skillRating": 90,
    "falaLeague": "Yes",
    "photoUrl": "",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": true
  },
  {
    "id": "p124",
    "name": "Yashaswy Alubaka",
    "gender": "Male",
    "role": "",
    "badminton": 90,
    "carroms": 90,
    "cricket": 90,
    "football": 90,
    "tableTennis": 90,
    "skillRating": 90,
    "falaLeague": "Yes",
    "photoUrl": "",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": true
  },
  {
    "id": "p125",
    "name": "Prathiksha Jakkannavar",
    "gender": "Female",
    "role": "",
    "badminton": 90,
    "carroms": 90,
    "cricket": 90,
    "football": 90,
    "tableTennis": 90,
    "skillRating": 90,
    "falaLeague": "Yes",
    "photoUrl": "",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": true
  },
  {
    "id": "p126",
    "name": "Saharsh Pandey",
    "gender": "Male",
    "role": "",
    "badminton": 90,
    "carroms": 90,
    "cricket": 90,
    "football": 90,
    "tableTennis": 90,
    "skillRating": 90,
    "falaLeague": "Yes",
    "photoUrl": "",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": true
  },
  {
    "id": "p127",
    "name": "Ganesh Jadi",
    "gender": "Male",
    "role": "",
    "badminton": 90,
    "carroms": 90,
    "cricket": 90,
    "football": 90,
    "tableTennis": 90,
    "skillRating": 90,
    "falaLeague": "Yes",
    "photoUrl": "",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": true
  },
  {
    "id": "p128",
    "name": "Kiran A",
    "gender": "Male",
    "role": "",
    "badminton": 90,
    "carroms": 90,
    "cricket": 90,
    "football": 90,
    "tableTennis": 90,
    "skillRating": 90,
    "falaLeague": "Yes",
    "photoUrl": "",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": true
  },
  {
    "id": "p129",
    "name": "Niranjan Kumar Singh",
    "gender": "Male",
    "role": "",
    "badminton": 90,
    "carroms": 90,
    "cricket": 90,
    "football": 90,
    "tableTennis": 90,
    "skillRating": 90,
    "falaLeague": "Yes",
    "photoUrl": "",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": true
  },
  {
    "id": "p130",
    "name": "Ganesan M",
    "gender": "Male",
    "role": "",
    "badminton": 90,
    "carroms": 90,
    "cricket": 90,
    "football": 90,
    "tableTennis": 90,
    "skillRating": 90,
    "falaLeague": "Yes",
    "photoUrl": "",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": true
  },
  {
    "id": "p131",
    "name": "Sharath HG",
    "gender": "Male",
    "role": "",
    "badminton": 90,
    "carroms": 90,
    "cricket": 90,
    "football": 90,
    "tableTennis": 90,
    "skillRating": 90,
    "falaLeague": "Yes",
    "photoUrl": "",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": true
  },
  {
    "id": "p132",
    "name": "Kartik Kapri",
    "gender": "Male",
    "role": "",
    "badminton": 90,
    "carroms": 90,
    "cricket": 90,
    "football": 90,
    "tableTennis": 90,
    "skillRating": 90,
    "falaLeague": "Yes",
    "photoUrl": "",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": true
  },
  {
    "id": "p133",
    "name": "Sravani Pula",
    "gender": "Female",
    "role": "",
    "badminton": 40,
    "carroms": 40,
    "cricket": 40,
    "football": 0,
    "tableTennis": 40,
    "skillRating": 40,
    "falaLeague": "No",
    "photoUrl": "",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p134",
    "name": "Karthik Badarinath",
    "gender": "Male",
    "role": "",
    "badminton": 0,
    "carroms": 40,
    "cricket": 40,
    "football": 0,
    "tableTennis": 0,
    "skillRating": 40,
    "falaLeague": "No",
    "photoUrl": "",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p135",
    "name": "Shweta jagannath",
    "gender": "Female",
    "role": "",
    "badminton": 40,
    "carroms": 40,
    "cricket": 0,
    "football": 0,
    "tableTennis": 0,
    "skillRating": 40,
    "falaLeague": "No",
    "photoUrl": "",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p136",
    "name": "Shivasai Telukuntla",
    "gender": "Male",
    "role": "",
    "badminton": 0,
    "carroms": 0,
    "cricket": 0,
    "football": 0,
    "tableTennis": 90,
    "skillRating": 90,
    "falaLeague": "No",
    "photoUrl": "",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p137",
    "name": "Rashish Jain",
    "gender": "Male",
    "role": "",
    "badminton": 70,
    "carroms": 70,
    "cricket": 40,
    "football": 70,
    "tableTennis": 70,
    "skillRating": 64,
    "falaLeague": "Yes",
    "photoUrl": "",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  },
  {
    "id": "p138",
    "name": "Vigneshwar Raj",
    "gender": "Male",
    "role": "",
    "badminton": 40,
    "carroms": 40,
    "cricket": 40,
    "football": 40,
    "tableTennis": 40,
    "skillRating": 60,
    "falaLeague": "No",
    "photoUrl": "",
    "isSold": false,
    "soldTo": null,
    "soldAmount": null,
    "isUnsold": false,
    "isOwnerOrCoOwner": false
  }
];

export const INITIAL_TEAMS = [
  { id: "t1", name: "Elite Eagle", owner: "Satheesh Kumar K", coOwner: "Tarani Prasad Pani", budget: 1000000, color: "#ef4444" },
  { id: "t2", name: "Ordervengers", owner: "Ganesh Jadi", coOwner: "Kiran A", budget: 1000000, color: "#3b82f6" },
  { id: "t3", name: "The Load Balancers", owner: "Vijay Anantpur", coOwner: "Iliyas Mulla", budget: 1000000, color: "#10b981" },
  { id: "t4", name: "The Groundbreakers", owner: "Naveen Vempati", coOwner: "Shashank Poojary", budget: 1000000, color: "#f59e0b" },
  { id: "t5", name: "Synergy Slayers", owner: "Yashaswy Alubaka", coOwner: "Yash Pendse", budget: 1000000, color: "#8b5cf6" },
  { id: "t6", name: "Falcon Fury", owner: "Sharath HG", coOwner: "Ganesan M", budget: 1000000, color: "#ec4899" },
  { id: "t7", name: "Ctl Alt Defeat", owner: "Niranjan Kumar Singh", coOwner: "Kartik Kapri", budget: 1000000, color: "#06b6d4" },
  { id: "t8", name: "EKAM", owner: "Prathiksha Jakkannavar", coOwner: "Saharsh Pandey", budget: 1000000, color: "#14b8a6" }
];
